// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models;

public partial class Gender
{
    [Key]
    [Column("GenderID")]
    public int GenderId { get; set; }

    [Column("Gender")]
    [StringLength(50)]
    [Unicode(false)]
    public string Gender1 { get; set; }

    [InverseProperty("GenderNavigation")]
    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}