// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Shared.Models;

public partial class Transaction
{
    [Key]
    public int TransactionId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string FirstName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LastName { get; set; }

    [Column("DOB", TypeName = "datetime")]
    public DateTime? Dob { get; set; }

    public int? Gender { get; set; }

    public int? Certification { get; set; }

    public int? Type { get; set; }

    [Unicode(false)]
    public string CostCenter { get; set; }

    public int? Site { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CreatedDate { get; set; }

    public int? Status { get; set; }

    [ForeignKey("Gender")]
    [InverseProperty("Transactions")]
    public virtual Gender GenderNavigation { get; set; }

    [ForeignKey("Site")]
    [InverseProperty("Transactions")]
    public virtual Site SiteNavigation { get; set; }

    [ForeignKey("Status")]
    [InverseProperty("Transactions")]
    public virtual Status StatusNavigation { get; set; }

    [ForeignKey("Type")]
    [InverseProperty("Transactions")]
    public virtual MineNumberType TypeNavigation { get; set; }
}